### ISSUE TITLE
TypeScript: "Cannot find module 'color-json' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ctsstc** [zvakanaka/color-json#2]
When I try to import color json I get an error of: 
> "Cannot find module 'color-json' or its corresponding type declarations.

## Code Example

```typescript
import colorJson from 'color-json'
```

## Version

`3.0.2`

I also tried 3.0.1 or 3.0.0.

## Additional

If I dig into my `node_modules/color-json` folder I see there's a `color-json.d.ts` in the root. The `package.json` shows that it should be exporting the type definition file, so it seems odd that it's not working 🤔 

I'm seeing on another project of mine the `package.json` has a top level key of `"types": "dist.index.d.ts"` but also doesn't have `"type": "module"`. That same `package.json` also has a `"main": "dist/index.js"` top level key as well.

It's also odd because the import breaks when going from v2 to v3. With v2 we told TS to ignore the error, but it could run. Now on v3 neither seems to work.

**Comment by ctsstc** [comment]
Closed by #3 

Thanks for releasing 3.0.3 @zvakanaka don't forget to tag the release here too it looks like ;)

**Comment by ctsstc** [comment]
@zvakanaka I'm now running into issues with jest where it says `Cannot find module 'color-json' from 'some-file.ts'` I know it's a jest problem, but during your transition to ESM across your packages have you found a way around this? I'm using `ts-jest` as a jest transformer, but that doesn't seem to help here.

**Comment by zvakanaka** [comment]
> @zvakanaka I'm now running into issues with jest where it says `Cannot find module 'color-json' from 'some-file.ts'` I know it's a jest problem, but during your transition to ESM across your packages have you found a way around this? I'm using `ts-jest` as a jest transformer, but that doesn't seem to help here.

@ctsstc 3.0.5 is published and should fix this. https://github.com/zvakanaka/color-json/pull/4 and https://github.com/zvakanaka/color-json/pull/5

**Comment by ctsstc** [comment]
Thanks, gave it a shot and now Jest is reporting error shenanigans as it should/would.

I ended up throwing a `__mocks__/color-json.ts` into my test root to auto-mock for the Jest ESM shenanigans that are currently ongoing.

`color-json.ts`

```ts
export default function colorJson(json: any): string {
  return JSON.stringify(json)
}
```
